[package]
name = "ker-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "engine"
path = "src/main.rs"

[dependencies]
ker-engine = { path = "../engine" }
clap = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
