[package]
name = "ker-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
glam = { workspace = true }
sha2 = { workspace = true }
hecs = { workspace = true }
image = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
